/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'markedBy' : TeacherId,
  'notes' : string,
  'courseId' : CourseId,
}
export type AttendanceStatus = { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export interface Batch {
  'id' : BatchId,
  'courses' : Array<CourseId>,
  'name' : string,
  'createdAt' : Timestamp,
  'year' : bigint,
}
export type BatchId = bigint;
export interface ClassSession {
  'id' : ScheduleId,
  'status' : ClassStatus,
  'topic' : string,
  'duration' : bigint,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'time' : string,
  'teacherId' : TeacherId,
  'courseId' : CourseId,
}
export type ClassStatus = { 'upcoming' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface Course {
  'id' : CourseId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'teacherId' : TeacherId,
  'batch' : BatchId,
  'schedule' : string,
}
export type CourseId = bigint;
export interface CreateAttendanceArgs {
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'notes' : string,
  'courseId' : CourseId,
}
export interface CreateBatchArgs { 'name' : string, 'year' : bigint }
export interface CreateCourseArgs {
  'name' : string,
  'description' : string,
  'teacherId' : TeacherId,
  'batch' : BatchId,
  'schedule' : string,
}
export interface CreateFeeArgs {
  'studentId' : StudentId,
  'feeType' : FeeType,
  'dueDate' : Timestamp,
  'notes' : string,
  'amount' : bigint,
}
export interface CreateMarkArgs {
  'marks' : bigint,
  'studentId' : StudentId,
  'date' : Timestamp,
  'maxMarks' : bigint,
  'examType' : string,
  'courseId' : CourseId,
  'remarks' : string,
}
export interface CreateMaterialArgs {
  'title' : string,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'courseId' : CourseId,
  'materialType' : MaterialType,
}
export interface CreateSessionArgs {
  'topic' : string,
  'duration' : bigint,
  'date' : Timestamp,
  'time' : string,
  'courseId' : CourseId,
}
export interface CreateStudentArgs {
  'name' : string,
  'joiningDate' : Timestamp,
  'email' : string,
  'batch' : BatchId,
}
export interface CreateTeacherArgs {
  'subjects' : Array<string>,
  'name' : string,
  'email' : string,
  'qualification' : string,
}
export interface DashboardAnalytics {
  'averageAttendance' : bigint,
  'feeCollectionRate' : bigint,
  'activeStudents' : bigint,
  'totalStudents' : bigint,
  'totalBatches' : bigint,
  'totalMaterials' : bigint,
  'totalTeachers' : bigint,
  'activeCourses' : bigint,
}
export type ExternalBlob = Uint8Array;
export type FeeId = bigint;
export type FeeStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export interface FeeTransaction {
  'id' : FeeId,
  'status' : FeeStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'feeType' : FeeType,
  'dueDate' : Timestamp,
  'paidDate' : [] | [Timestamp],
  'notes' : string,
  'amount' : bigint,
}
export type FeeType = { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export interface Mark {
  'id' : MarkId,
  'marks' : bigint,
  'studentId' : StudentId,
  'date' : Timestamp,
  'recordedBy' : TeacherId,
  'maxMarks' : bigint,
  'examType' : string,
  'courseId' : CourseId,
  'remarks' : string,
}
export type MarkId = bigint;
export type MaterialId = bigint;
export type MaterialType = { 'resource' : null } |
  { 'assignment' : null } |
  { 'notes' : null };
export type ScheduleId = bigint;
export type StudentId = bigint;
export interface StudentPerformanceSummary {
  'marks' : Array<MarkId>,
  'studentId' : StudentId,
  'totalExams' : bigint,
  'averagePercentage' : bigint,
  'courseId' : CourseId,
}
export interface StudentProfile {
  'id' : StudentId,
  'principal' : Principal,
  'name' : string,
  'joiningDate' : Timestamp,
  'isActive' : boolean,
  'email' : string,
  'batch' : BatchId,
  'enrolledCourses' : Array<CourseId>,
}
export interface StudyMaterial {
  'id' : MaterialId,
  'title' : string,
  'fileBlob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'courseId' : CourseId,
  'uploadDate' : Timestamp,
  'materialType' : MaterialType,
  'uploadedBy' : TeacherId,
}
export type TeacherId = bigint;
export interface TeacherProfile {
  'id' : TeacherId,
  'principal' : Principal,
  'subjects' : Array<string>,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'joinedDate' : Timestamp,
  'qualification' : string,
}
export type Timestamp = bigint;
export interface UpdateCourseArgs {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'teacherId' : TeacherId,
  'batch' : BatchId,
  'schedule' : string,
}
export interface UpdateFeeArgs {
  'status' : FeeStatus,
  'feeType' : FeeType,
  'dueDate' : Timestamp,
  'paidDate' : [] | [Timestamp],
  'notes' : string,
  'amount' : bigint,
}
export interface UpdateSessionArgs {
  'status' : ClassStatus,
  'topic' : string,
  'duration' : bigint,
  'date' : Timestamp,
  'time' : string,
}
export interface UpdateStudentArgs {
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'batch' : BatchId,
}
export interface UpdateTeacherArgs {
  'subjects' : Array<string>,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'qualification' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSession' : ActorMethod<[ScheduleId], undefined>,
  'createBatch' : ActorMethod<[CreateBatchArgs], Batch>,
  'createCourse' : ActorMethod<[CreateCourseArgs], Course>,
  'createFee' : ActorMethod<[CreateFeeArgs], FeeTransaction>,
  'createSession' : ActorMethod<[CreateSessionArgs], ClassSession>,
  'createStudent' : ActorMethod<[CreateStudentArgs], StudentProfile>,
  'createTeacher' : ActorMethod<[Principal, CreateTeacherArgs], TeacherProfile>,
  'deleteMaterial' : ActorMethod<[MaterialId], undefined>,
  'deleteStudent' : ActorMethod<[StudentId], undefined>,
  'deleteTeacher' : ActorMethod<[TeacherId], undefined>,
  'enrollStudentInCourse' : ActorMethod<[StudentId, CourseId], undefined>,
  'getAttendanceRate' : ActorMethod<[StudentId, CourseId], bigint>,
  'getBatch' : ActorMethod<[BatchId], [] | [Batch]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getDashboardAnalytics' : ActorMethod<[], DashboardAnalytics>,
  'getFee' : ActorMethod<[FeeId], [] | [FeeTransaction]>,
  'getFeeCollectionRate' : ActorMethod<[], bigint>,
  'getMaterial' : ActorMethod<[MaterialId], [] | [StudyMaterial]>,
  'getMyStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getMyTeacherProfile' : ActorMethod<[], [] | [TeacherProfile]>,
  'getPerformanceSummary' : ActorMethod<
    [StudentId, CourseId],
    StudentPerformanceSummary
  >,
  'getSession' : ActorMethod<[ScheduleId], [] | [ClassSession]>,
  'getStudent' : ActorMethod<[StudentId], [] | [StudentProfile]>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [TeacherProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAttendanceByCourse' : ActorMethod<[CourseId], Array<AttendanceRecord>>,
  'listAttendanceByDate' : ActorMethod<
    [CourseId, Timestamp],
    Array<AttendanceRecord>
  >,
  'listAttendanceByStudent' : ActorMethod<[StudentId], Array<AttendanceRecord>>,
  'listBatches' : ActorMethod<[], Array<Batch>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listCoursesByBatch' : ActorMethod<[BatchId], Array<Course>>,
  'listCoursesByTeacher' : ActorMethod<[TeacherId], Array<Course>>,
  'listFees' : ActorMethod<[], Array<FeeTransaction>>,
  'listFeesByStudent' : ActorMethod<[StudentId], Array<FeeTransaction>>,
  'listMarksByCourse' : ActorMethod<[CourseId], Array<Mark>>,
  'listMarksByStudent' : ActorMethod<[StudentId], Array<Mark>>,
  'listMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'listMaterialsByCourse' : ActorMethod<[CourseId], Array<StudyMaterial>>,
  'listSessionsByCourse' : ActorMethod<[CourseId], Array<ClassSession>>,
  'listSessionsByTeacher' : ActorMethod<[TeacherId], Array<ClassSession>>,
  'listStudents' : ActorMethod<[], Array<StudentProfile>>,
  'listTeachers' : ActorMethod<[], Array<TeacherProfile>>,
  'recordAttendance' : ActorMethod<[CreateAttendanceArgs], AttendanceRecord>,
  'recordMark' : ActorMethod<[CreateMarkArgs], Mark>,
  'seedDemoData' : ActorMethod<[], string>,
  'unenrollStudentFromCourse' : ActorMethod<[StudentId, CourseId], undefined>,
  'updateCourse' : ActorMethod<[CourseId, UpdateCourseArgs], undefined>,
  'updateFee' : ActorMethod<[FeeId, UpdateFeeArgs], undefined>,
  'updateSession' : ActorMethod<[ScheduleId, UpdateSessionArgs], undefined>,
  'updateStudent' : ActorMethod<[StudentId, UpdateStudentArgs], undefined>,
  'updateTeacher' : ActorMethod<[TeacherId, UpdateTeacherArgs], undefined>,
  'uploadMaterial' : ActorMethod<[CreateMaterialArgs], StudyMaterial>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];