/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScheduleId = IDL.Nat;
export const CreateBatchArgs = IDL.Record({
  'name' : IDL.Text,
  'year' : IDL.Nat,
});
export const BatchId = IDL.Nat;
export const CourseId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Batch = IDL.Record({
  'id' : BatchId,
  'courses' : IDL.Vec(CourseId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
});
export const TeacherId = IDL.Nat;
export const CreateCourseArgs = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'teacherId' : TeacherId,
  'batch' : BatchId,
  'schedule' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : CourseId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'teacherId' : TeacherId,
  'batch' : BatchId,
  'schedule' : IDL.Text,
});
export const StudentId = IDL.Nat;
export const FeeType = IDL.Variant({
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const CreateFeeArgs = IDL.Record({
  'studentId' : StudentId,
  'feeType' : FeeType,
  'dueDate' : Timestamp,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const FeeId = IDL.Nat;
export const FeeStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const FeeTransaction = IDL.Record({
  'id' : FeeId,
  'status' : FeeStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'feeType' : FeeType,
  'dueDate' : Timestamp,
  'paidDate' : IDL.Opt(Timestamp),
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const CreateSessionArgs = IDL.Record({
  'topic' : IDL.Text,
  'duration' : IDL.Nat,
  'date' : Timestamp,
  'time' : IDL.Text,
  'courseId' : CourseId,
});
export const ClassStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const ClassSession = IDL.Record({
  'id' : ScheduleId,
  'status' : ClassStatus,
  'topic' : IDL.Text,
  'duration' : IDL.Nat,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'teacherId' : TeacherId,
  'courseId' : CourseId,
});
export const CreateStudentArgs = IDL.Record({
  'name' : IDL.Text,
  'joiningDate' : Timestamp,
  'email' : IDL.Text,
  'batch' : BatchId,
});
export const StudentProfile = IDL.Record({
  'id' : StudentId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'joiningDate' : Timestamp,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'batch' : BatchId,
  'enrolledCourses' : IDL.Vec(CourseId),
});
export const CreateTeacherArgs = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'qualification' : IDL.Text,
});
export const TeacherProfile = IDL.Record({
  'id' : TeacherId,
  'principal' : IDL.Principal,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'joinedDate' : Timestamp,
  'qualification' : IDL.Text,
});
export const MaterialId = IDL.Nat;
export const DashboardAnalytics = IDL.Record({
  'averageAttendance' : IDL.Nat,
  'feeCollectionRate' : IDL.Nat,
  'activeStudents' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'totalBatches' : IDL.Nat,
  'totalMaterials' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'activeCourses' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MaterialType = IDL.Variant({
  'resource' : IDL.Null,
  'assignment' : IDL.Null,
  'notes' : IDL.Null,
});
export const StudyMaterial = IDL.Record({
  'id' : MaterialId,
  'title' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'courseId' : CourseId,
  'uploadDate' : Timestamp,
  'materialType' : MaterialType,
  'uploadedBy' : TeacherId,
});
export const MarkId = IDL.Nat;
export const StudentPerformanceSummary = IDL.Record({
  'marks' : IDL.Vec(MarkId),
  'studentId' : StudentId,
  'totalExams' : IDL.Nat,
  'averagePercentage' : IDL.Nat,
  'courseId' : CourseId,
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'markedBy' : TeacherId,
  'notes' : IDL.Text,
  'courseId' : CourseId,
});
export const Mark = IDL.Record({
  'id' : MarkId,
  'marks' : IDL.Nat,
  'studentId' : StudentId,
  'date' : Timestamp,
  'recordedBy' : TeacherId,
  'maxMarks' : IDL.Nat,
  'examType' : IDL.Text,
  'courseId' : CourseId,
  'remarks' : IDL.Text,
});
export const CreateAttendanceArgs = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'notes' : IDL.Text,
  'courseId' : CourseId,
});
export const CreateMarkArgs = IDL.Record({
  'marks' : IDL.Nat,
  'studentId' : StudentId,
  'date' : Timestamp,
  'maxMarks' : IDL.Nat,
  'examType' : IDL.Text,
  'courseId' : CourseId,
  'remarks' : IDL.Text,
});
export const UpdateCourseArgs = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'teacherId' : TeacherId,
  'batch' : BatchId,
  'schedule' : IDL.Text,
});
export const UpdateFeeArgs = IDL.Record({
  'status' : FeeStatus,
  'feeType' : FeeType,
  'dueDate' : Timestamp,
  'paidDate' : IDL.Opt(Timestamp),
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UpdateSessionArgs = IDL.Record({
  'status' : ClassStatus,
  'topic' : IDL.Text,
  'duration' : IDL.Nat,
  'date' : Timestamp,
  'time' : IDL.Text,
});
export const UpdateStudentArgs = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'batch' : BatchId,
});
export const UpdateTeacherArgs = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'qualification' : IDL.Text,
});
export const CreateMaterialArgs = IDL.Record({
  'title' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'courseId' : CourseId,
  'materialType' : MaterialType,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSession' : IDL.Func([ScheduleId], [], []),
  'createBatch' : IDL.Func([CreateBatchArgs], [Batch], []),
  'createCourse' : IDL.Func([CreateCourseArgs], [Course], []),
  'createFee' : IDL.Func([CreateFeeArgs], [FeeTransaction], []),
  'createSession' : IDL.Func([CreateSessionArgs], [ClassSession], []),
  'createStudent' : IDL.Func([CreateStudentArgs], [StudentProfile], []),
  'createTeacher' : IDL.Func(
      [IDL.Principal, CreateTeacherArgs],
      [TeacherProfile],
      [],
    ),
  'deleteMaterial' : IDL.Func([MaterialId], [], []),
  'deleteStudent' : IDL.Func([StudentId], [], []),
  'deleteTeacher' : IDL.Func([TeacherId], [], []),
  'enrollStudentInCourse' : IDL.Func([StudentId, CourseId], [], []),
  'getAttendanceRate' : IDL.Func([StudentId, CourseId], [IDL.Nat], ['query']),
  'getBatch' : IDL.Func([BatchId], [IDL.Opt(Batch)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getDashboardAnalytics' : IDL.Func([], [DashboardAnalytics], ['query']),
  'getFee' : IDL.Func([FeeId], [IDL.Opt(FeeTransaction)], ['query']),
  'getFeeCollectionRate' : IDL.Func([], [IDL.Nat], ['query']),
  'getMaterial' : IDL.Func([MaterialId], [IDL.Opt(StudyMaterial)], ['query']),
  'getMyStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getMyTeacherProfile' : IDL.Func([], [IDL.Opt(TeacherProfile)], ['query']),
  'getPerformanceSummary' : IDL.Func(
      [StudentId, CourseId],
      [StudentPerformanceSummary],
      ['query'],
    ),
  'getSession' : IDL.Func([ScheduleId], [IDL.Opt(ClassSession)], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentProfile)], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(TeacherProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAttendanceByCourse' : IDL.Func(
      [CourseId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listAttendanceByDate' : IDL.Func(
      [CourseId, Timestamp],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listAttendanceByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'listBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listCoursesByBatch' : IDL.Func([BatchId], [IDL.Vec(Course)], ['query']),
  'listCoursesByTeacher' : IDL.Func([TeacherId], [IDL.Vec(Course)], ['query']),
  'listFees' : IDL.Func([], [IDL.Vec(FeeTransaction)], ['query']),
  'listFeesByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeeTransaction)],
      ['query'],
    ),
  'listMarksByCourse' : IDL.Func([CourseId], [IDL.Vec(Mark)], ['query']),
  'listMarksByStudent' : IDL.Func([StudentId], [IDL.Vec(Mark)], ['query']),
  'listMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'listMaterialsByCourse' : IDL.Func(
      [CourseId],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'listSessionsByCourse' : IDL.Func(
      [CourseId],
      [IDL.Vec(ClassSession)],
      ['query'],
    ),
  'listSessionsByTeacher' : IDL.Func(
      [TeacherId],
      [IDL.Vec(ClassSession)],
      ['query'],
    ),
  'listStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'recordAttendance' : IDL.Func([CreateAttendanceArgs], [AttendanceRecord], []),
  'recordMark' : IDL.Func([CreateMarkArgs], [Mark], []),
  'seedDemoData' : IDL.Func([], [IDL.Text], []),
  'unenrollStudentFromCourse' : IDL.Func([StudentId, CourseId], [], []),
  'updateCourse' : IDL.Func([CourseId, UpdateCourseArgs], [], []),
  'updateFee' : IDL.Func([FeeId, UpdateFeeArgs], [], []),
  'updateSession' : IDL.Func([ScheduleId, UpdateSessionArgs], [], []),
  'updateStudent' : IDL.Func([StudentId, UpdateStudentArgs], [], []),
  'updateTeacher' : IDL.Func([TeacherId, UpdateTeacherArgs], [], []),
  'uploadMaterial' : IDL.Func([CreateMaterialArgs], [StudyMaterial], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScheduleId = IDL.Nat;
  const CreateBatchArgs = IDL.Record({ 'name' : IDL.Text, 'year' : IDL.Nat });
  const BatchId = IDL.Nat;
  const CourseId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Batch = IDL.Record({
    'id' : BatchId,
    'courses' : IDL.Vec(CourseId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
  });
  const TeacherId = IDL.Nat;
  const CreateCourseArgs = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'teacherId' : TeacherId,
    'batch' : BatchId,
    'schedule' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'teacherId' : TeacherId,
    'batch' : BatchId,
    'schedule' : IDL.Text,
  });
  const StudentId = IDL.Nat;
  const FeeType = IDL.Variant({
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const CreateFeeArgs = IDL.Record({
    'studentId' : StudentId,
    'feeType' : FeeType,
    'dueDate' : Timestamp,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const FeeId = IDL.Nat;
  const FeeStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const FeeTransaction = IDL.Record({
    'id' : FeeId,
    'status' : FeeStatus,
    'studentId' : StudentId,
    'createdAt' : Timestamp,
    'feeType' : FeeType,
    'dueDate' : Timestamp,
    'paidDate' : IDL.Opt(Timestamp),
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const CreateSessionArgs = IDL.Record({
    'topic' : IDL.Text,
    'duration' : IDL.Nat,
    'date' : Timestamp,
    'time' : IDL.Text,
    'courseId' : CourseId,
  });
  const ClassStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const ClassSession = IDL.Record({
    'id' : ScheduleId,
    'status' : ClassStatus,
    'topic' : IDL.Text,
    'duration' : IDL.Nat,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'teacherId' : TeacherId,
    'courseId' : CourseId,
  });
  const CreateStudentArgs = IDL.Record({
    'name' : IDL.Text,
    'joiningDate' : Timestamp,
    'email' : IDL.Text,
    'batch' : BatchId,
  });
  const StudentProfile = IDL.Record({
    'id' : StudentId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'joiningDate' : Timestamp,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'batch' : BatchId,
    'enrolledCourses' : IDL.Vec(CourseId),
  });
  const CreateTeacherArgs = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const TeacherProfile = IDL.Record({
    'id' : TeacherId,
    'principal' : IDL.Principal,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'joinedDate' : Timestamp,
    'qualification' : IDL.Text,
  });
  const MaterialId = IDL.Nat;
  const DashboardAnalytics = IDL.Record({
    'averageAttendance' : IDL.Nat,
    'feeCollectionRate' : IDL.Nat,
    'activeStudents' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'totalBatches' : IDL.Nat,
    'totalMaterials' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'activeCourses' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MaterialType = IDL.Variant({
    'resource' : IDL.Null,
    'assignment' : IDL.Null,
    'notes' : IDL.Null,
  });
  const StudyMaterial = IDL.Record({
    'id' : MaterialId,
    'title' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'courseId' : CourseId,
    'uploadDate' : Timestamp,
    'materialType' : MaterialType,
    'uploadedBy' : TeacherId,
  });
  const MarkId = IDL.Nat;
  const StudentPerformanceSummary = IDL.Record({
    'marks' : IDL.Vec(MarkId),
    'studentId' : StudentId,
    'totalExams' : IDL.Nat,
    'averagePercentage' : IDL.Nat,
    'courseId' : CourseId,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : Timestamp,
    'markedBy' : TeacherId,
    'notes' : IDL.Text,
    'courseId' : CourseId,
  });
  const Mark = IDL.Record({
    'id' : MarkId,
    'marks' : IDL.Nat,
    'studentId' : StudentId,
    'date' : Timestamp,
    'recordedBy' : TeacherId,
    'maxMarks' : IDL.Nat,
    'examType' : IDL.Text,
    'courseId' : CourseId,
    'remarks' : IDL.Text,
  });
  const CreateAttendanceArgs = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : Timestamp,
    'notes' : IDL.Text,
    'courseId' : CourseId,
  });
  const CreateMarkArgs = IDL.Record({
    'marks' : IDL.Nat,
    'studentId' : StudentId,
    'date' : Timestamp,
    'maxMarks' : IDL.Nat,
    'examType' : IDL.Text,
    'courseId' : CourseId,
    'remarks' : IDL.Text,
  });
  const UpdateCourseArgs = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'teacherId' : TeacherId,
    'batch' : BatchId,
    'schedule' : IDL.Text,
  });
  const UpdateFeeArgs = IDL.Record({
    'status' : FeeStatus,
    'feeType' : FeeType,
    'dueDate' : Timestamp,
    'paidDate' : IDL.Opt(Timestamp),
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UpdateSessionArgs = IDL.Record({
    'status' : ClassStatus,
    'topic' : IDL.Text,
    'duration' : IDL.Nat,
    'date' : Timestamp,
    'time' : IDL.Text,
  });
  const UpdateStudentArgs = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'batch' : BatchId,
  });
  const UpdateTeacherArgs = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const CreateMaterialArgs = IDL.Record({
    'title' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'courseId' : CourseId,
    'materialType' : MaterialType,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSession' : IDL.Func([ScheduleId], [], []),
    'createBatch' : IDL.Func([CreateBatchArgs], [Batch], []),
    'createCourse' : IDL.Func([CreateCourseArgs], [Course], []),
    'createFee' : IDL.Func([CreateFeeArgs], [FeeTransaction], []),
    'createSession' : IDL.Func([CreateSessionArgs], [ClassSession], []),
    'createStudent' : IDL.Func([CreateStudentArgs], [StudentProfile], []),
    'createTeacher' : IDL.Func(
        [IDL.Principal, CreateTeacherArgs],
        [TeacherProfile],
        [],
      ),
    'deleteMaterial' : IDL.Func([MaterialId], [], []),
    'deleteStudent' : IDL.Func([StudentId], [], []),
    'deleteTeacher' : IDL.Func([TeacherId], [], []),
    'enrollStudentInCourse' : IDL.Func([StudentId, CourseId], [], []),
    'getAttendanceRate' : IDL.Func([StudentId, CourseId], [IDL.Nat], ['query']),
    'getBatch' : IDL.Func([BatchId], [IDL.Opt(Batch)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getDashboardAnalytics' : IDL.Func([], [DashboardAnalytics], ['query']),
    'getFee' : IDL.Func([FeeId], [IDL.Opt(FeeTransaction)], ['query']),
    'getFeeCollectionRate' : IDL.Func([], [IDL.Nat], ['query']),
    'getMaterial' : IDL.Func([MaterialId], [IDL.Opt(StudyMaterial)], ['query']),
    'getMyStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getMyTeacherProfile' : IDL.Func([], [IDL.Opt(TeacherProfile)], ['query']),
    'getPerformanceSummary' : IDL.Func(
        [StudentId, CourseId],
        [StudentPerformanceSummary],
        ['query'],
      ),
    'getSession' : IDL.Func([ScheduleId], [IDL.Opt(ClassSession)], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentProfile)], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(TeacherProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAttendanceByCourse' : IDL.Func(
        [CourseId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listAttendanceByDate' : IDL.Func(
        [CourseId, Timestamp],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listAttendanceByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'listBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listCoursesByBatch' : IDL.Func([BatchId], [IDL.Vec(Course)], ['query']),
    'listCoursesByTeacher' : IDL.Func(
        [TeacherId],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'listFees' : IDL.Func([], [IDL.Vec(FeeTransaction)], ['query']),
    'listFeesByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeeTransaction)],
        ['query'],
      ),
    'listMarksByCourse' : IDL.Func([CourseId], [IDL.Vec(Mark)], ['query']),
    'listMarksByStudent' : IDL.Func([StudentId], [IDL.Vec(Mark)], ['query']),
    'listMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'listMaterialsByCourse' : IDL.Func(
        [CourseId],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'listSessionsByCourse' : IDL.Func(
        [CourseId],
        [IDL.Vec(ClassSession)],
        ['query'],
      ),
    'listSessionsByTeacher' : IDL.Func(
        [TeacherId],
        [IDL.Vec(ClassSession)],
        ['query'],
      ),
    'listStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'recordAttendance' : IDL.Func(
        [CreateAttendanceArgs],
        [AttendanceRecord],
        [],
      ),
    'recordMark' : IDL.Func([CreateMarkArgs], [Mark], []),
    'seedDemoData' : IDL.Func([], [IDL.Text], []),
    'unenrollStudentFromCourse' : IDL.Func([StudentId, CourseId], [], []),
    'updateCourse' : IDL.Func([CourseId, UpdateCourseArgs], [], []),
    'updateFee' : IDL.Func([FeeId, UpdateFeeArgs], [], []),
    'updateSession' : IDL.Func([ScheduleId, UpdateSessionArgs], [], []),
    'updateStudent' : IDL.Func([StudentId, UpdateStudentArgs], [], []),
    'updateTeacher' : IDL.Func([TeacherId, UpdateTeacherArgs], [], []),
    'uploadMaterial' : IDL.Func([CreateMaterialArgs], [StudyMaterial], []),
  });
};

export const init = ({ IDL }) => { return []; };