/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateMaterialArgs {
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    courseId: CourseId;
    materialType: MaterialType;
}
export interface CreateBatchArgs {
    name: string;
    year: bigint;
}
export interface CreateFeeArgs {
    studentId: StudentId;
    feeType: FeeType;
    dueDate: Timestamp;
    notes: string;
    amount: bigint;
}
export interface FeeTransaction {
    id: FeeId;
    status: FeeStatus;
    studentId: StudentId;
    createdAt: Timestamp;
    feeType: FeeType;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    notes: string;
    amount: bigint;
}
export type AttendanceId = bigint;
export interface UpdateTeacherArgs {
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    qualification: string;
}
export type BatchId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Course {
    id: CourseId;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    teacherId: TeacherId;
    batch: BatchId;
    schedule: string;
}
export type MarkId = bigint;
export type FeeId = bigint;
export interface CreateSessionArgs {
    topic: string;
    duration: bigint;
    date: Timestamp;
    time: string;
    courseId: CourseId;
}
export interface StudyMaterial {
    id: MaterialId;
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    courseId: CourseId;
    uploadDate: Timestamp;
    materialType: MaterialType;
    uploadedBy: TeacherId;
}
export interface Mark {
    id: MarkId;
    marks: bigint;
    studentId: StudentId;
    date: Timestamp;
    recordedBy: TeacherId;
    maxMarks: bigint;
    examType: string;
    courseId: CourseId;
    remarks: string;
}
export type CourseId = bigint;
export interface Batch {
    id: BatchId;
    courses: Array<CourseId>;
    name: string;
    createdAt: Timestamp;
    year: bigint;
}
export interface UpdateCourseArgs {
    name: string;
    description: string;
    isActive: boolean;
    teacherId: TeacherId;
    batch: BatchId;
    schedule: string;
}
export interface CreateAttendanceArgs {
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    notes: string;
    courseId: CourseId;
}
export interface AttendanceRecord {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    markedBy: TeacherId;
    notes: string;
    courseId: CourseId;
}
export interface DashboardAnalytics {
    averageAttendance: bigint;
    feeCollectionRate: bigint;
    activeStudents: bigint;
    totalStudents: bigint;
    totalBatches: bigint;
    totalMaterials: bigint;
    totalTeachers: bigint;
    activeCourses: bigint;
}
export interface UpdateFeeArgs {
    status: FeeStatus;
    feeType: FeeType;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    notes: string;
    amount: bigint;
}
export interface StudentPerformanceSummary {
    marks: Array<MarkId>;
    studentId: StudentId;
    totalExams: bigint;
    averagePercentage: bigint;
    courseId: CourseId;
}
export interface CreateTeacherArgs {
    subjects: Array<string>;
    name: string;
    email: string;
    qualification: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CreateMarkArgs {
    marks: bigint;
    studentId: StudentId;
    date: Timestamp;
    maxMarks: bigint;
    examType: string;
    courseId: CourseId;
    remarks: string;
}
export type StudentId = bigint;
export type TeacherId = bigint;
export interface TeacherProfile {
    id: TeacherId;
    principal: Principal;
    subjects: Array<string>;
    name: string;
    isActive: boolean;
    email: string;
    joinedDate: Timestamp;
    qualification: string;
}
export type MaterialId = bigint;
export interface StudentProfile {
    id: StudentId;
    principal: Principal;
    name: string;
    joiningDate: Timestamp;
    isActive: boolean;
    email: string;
    batch: BatchId;
    enrolledCourses: Array<CourseId>;
}
export type ScheduleId = bigint;
export interface CreateCourseArgs {
    name: string;
    description: string;
    teacherId: TeacherId;
    batch: BatchId;
    schedule: string;
}
export interface ClassSession {
    id: ScheduleId;
    status: ClassStatus;
    topic: string;
    duration: bigint;
    date: Timestamp;
    createdAt: Timestamp;
    time: string;
    teacherId: TeacherId;
    courseId: CourseId;
}
export interface UpdateSessionArgs {
    status: ClassStatus;
    topic: string;
    duration: bigint;
    date: Timestamp;
    time: string;
}
export interface UpdateStudentArgs {
    name: string;
    isActive: boolean;
    email: string;
    batch: BatchId;
}
export interface CreateStudentArgs {
    name: string;
    joiningDate: Timestamp;
    email: string;
    batch: BatchId;
}
export enum AttendanceStatus {
    present = "present",
    late = "late",
    absent = "absent"
}
export enum ClassStatus {
    upcoming = "upcoming",
    cancelled = "cancelled",
    completed = "completed"
}
export enum FeeStatus {
    paid = "paid",
    unpaid = "unpaid",
    partial = "partial"
}
export enum FeeType {
    annual = "annual",
    quarterly = "quarterly",
    monthly = "monthly"
}
export enum MaterialType {
    resource = "resource",
    assignment = "assignment",
    notes = "notes"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelSession(id: ScheduleId): Promise<void>;
    createBatch(args: CreateBatchArgs): Promise<Batch>;
    createCourse(args: CreateCourseArgs): Promise<Course>;
    createFee(args: CreateFeeArgs): Promise<FeeTransaction>;
    createSession(args: CreateSessionArgs): Promise<ClassSession>;
    createStudent(args: CreateStudentArgs): Promise<StudentProfile>;
    createTeacher(principal: Principal, args: CreateTeacherArgs): Promise<TeacherProfile>;
    deleteMaterial(id: MaterialId): Promise<void>;
    deleteStudent(id: StudentId): Promise<void>;
    deleteTeacher(id: TeacherId): Promise<void>;
    enrollStudentInCourse(studentId: StudentId, courseId: CourseId): Promise<void>;
    getAttendanceRate(studentId: StudentId, courseId: CourseId): Promise<bigint>;
    getBatch(id: BatchId): Promise<Batch | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(id: CourseId): Promise<Course | null>;
    getDashboardAnalytics(): Promise<DashboardAnalytics>;
    getFee(id: FeeId): Promise<FeeTransaction | null>;
    getFeeCollectionRate(): Promise<bigint>;
    getMaterial(id: MaterialId): Promise<StudyMaterial | null>;
    getMyStudentProfile(): Promise<StudentProfile | null>;
    getMyTeacherProfile(): Promise<TeacherProfile | null>;
    getPerformanceSummary(studentId: StudentId, courseId: CourseId): Promise<StudentPerformanceSummary>;
    getSession(id: ScheduleId): Promise<ClassSession | null>;
    getStudent(id: StudentId): Promise<StudentProfile | null>;
    getTeacher(id: TeacherId): Promise<TeacherProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAttendanceByCourse(courseId: CourseId): Promise<Array<AttendanceRecord>>;
    listAttendanceByDate(courseId: CourseId, date: Timestamp): Promise<Array<AttendanceRecord>>;
    listAttendanceByStudent(studentId: StudentId): Promise<Array<AttendanceRecord>>;
    listBatches(): Promise<Array<Batch>>;
    listCourses(): Promise<Array<Course>>;
    listCoursesByBatch(batchId: BatchId): Promise<Array<Course>>;
    listCoursesByTeacher(teacherId: TeacherId): Promise<Array<Course>>;
    listFees(): Promise<Array<FeeTransaction>>;
    listFeesByStudent(studentId: StudentId): Promise<Array<FeeTransaction>>;
    listMarksByCourse(courseId: CourseId): Promise<Array<Mark>>;
    listMarksByStudent(studentId: StudentId): Promise<Array<Mark>>;
    listMaterials(): Promise<Array<StudyMaterial>>;
    listMaterialsByCourse(courseId: CourseId): Promise<Array<StudyMaterial>>;
    listSessionsByCourse(courseId: CourseId): Promise<Array<ClassSession>>;
    listSessionsByTeacher(teacherId: TeacherId): Promise<Array<ClassSession>>;
    listStudents(): Promise<Array<StudentProfile>>;
    listTeachers(): Promise<Array<TeacherProfile>>;
    recordAttendance(args: CreateAttendanceArgs): Promise<AttendanceRecord>;
    recordMark(args: CreateMarkArgs): Promise<Mark>;
    seedDemoData(): Promise<string>;
    unenrollStudentFromCourse(studentId: StudentId, courseId: CourseId): Promise<void>;
    updateCourse(id: CourseId, args: UpdateCourseArgs): Promise<void>;
    updateFee(id: FeeId, args: UpdateFeeArgs): Promise<void>;
    updateSession(id: ScheduleId, args: UpdateSessionArgs): Promise<void>;
    updateStudent(id: StudentId, args: UpdateStudentArgs): Promise<void>;
    updateTeacher(id: TeacherId, args: UpdateTeacherArgs): Promise<void>;
    uploadMaterial(args: CreateMaterialArgs): Promise<StudyMaterial>;
}
import type { AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, Batch as _Batch, ClassSession as _ClassSession, ClassStatus as _ClassStatus, Course as _Course, CourseId as _CourseId, CreateAttendanceArgs as _CreateAttendanceArgs, CreateFeeArgs as _CreateFeeArgs, CreateMaterialArgs as _CreateMaterialArgs, ExternalBlob as _ExternalBlob, FeeId as _FeeId, FeeStatus as _FeeStatus, FeeTransaction as _FeeTransaction, FeeType as _FeeType, MaterialId as _MaterialId, MaterialType as _MaterialType, ScheduleId as _ScheduleId, StudentId as _StudentId, StudentProfile as _StudentProfile, StudyMaterial as _StudyMaterial, TeacherId as _TeacherId, TeacherProfile as _TeacherProfile, Timestamp as _Timestamp, UpdateFeeArgs as _UpdateFeeArgs, UpdateSessionArgs as _UpdateSessionArgs, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelSession(arg0: ScheduleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSession(arg0);
            return result;
        }
    }
    async createBatch(arg0: CreateBatchArgs): Promise<Batch> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatch(arg0);
            return result;
        }
    }
    async createCourse(arg0: CreateCourseArgs): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return result;
        }
    }
    async createFee(arg0: CreateFeeArgs): Promise<FeeTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.createFee(to_candid_CreateFeeArgs_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FeeTransaction_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFee(to_candid_CreateFeeArgs_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FeeTransaction_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSession(arg0: CreateSessionArgs): Promise<ClassSession> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return from_candid_ClassSession_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return from_candid_ClassSession_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: CreateStudentArgs): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return result;
        }
    }
    async createTeacher(arg0: Principal, arg1: CreateTeacherArgs): Promise<TeacherProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(arg0, arg1);
            return result;
        }
    }
    async deleteMaterial(arg0: MaterialId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: TeacherId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async enrollStudentInCourse(arg0: StudentId, arg1: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollStudentInCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollStudentInCourse(arg0, arg1);
            return result;
        }
    }
    async getAttendanceRate(arg0: StudentId, arg1: CourseId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceRate(arg0, arg1);
            return result;
        }
    }
    async getBatch(arg0: BatchId): Promise<Batch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatch(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatch(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: CourseId): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardAnalytics(): Promise<DashboardAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardAnalytics();
            return result;
        }
    }
    async getFee(arg0: FeeId): Promise<FeeTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFee(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFee(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeCollectionRate(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeCollectionRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeCollectionRate();
            return result;
        }
    }
    async getMaterial(arg0: MaterialId): Promise<StudyMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterial(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterial(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStudentProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStudentProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStudentProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTeacherProfile(): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTeacherProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTeacherProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceSummary(arg0: StudentId, arg1: CourseId): Promise<StudentPerformanceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceSummary(arg0, arg1);
            return result;
        }
    }
    async getSession(arg0: ScheduleId): Promise<ClassSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: TeacherId): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAttendanceByCourse(arg0: CourseId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendanceByCourse(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendanceByCourse(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAttendanceByDate(arg0: CourseId, arg1: Timestamp): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendanceByDate(arg0, arg1);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendanceByDate(arg0, arg1);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAttendanceByStudent(arg0: StudentId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAttendanceByStudent(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAttendanceByStudent(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBatches();
            return result;
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return result;
        }
    }
    async listCoursesByBatch(arg0: BatchId): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoursesByBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoursesByBatch(arg0);
            return result;
        }
    }
    async listCoursesByTeacher(arg0: TeacherId): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoursesByTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoursesByTeacher(arg0);
            return result;
        }
    }
    async listFees(): Promise<Array<FeeTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFees();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFees();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeesByStudent(arg0: StudentId): Promise<Array<FeeTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeesByStudent(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeesByStudent(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMarksByCourse(arg0: CourseId): Promise<Array<Mark>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMarksByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMarksByCourse(arg0);
            return result;
        }
    }
    async listMarksByStudent(arg0: StudentId): Promise<Array<Mark>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMarksByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMarksByStudent(arg0);
            return result;
        }
    }
    async listMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaterials();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaterials();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMaterialsByCourse(arg0: CourseId): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaterialsByCourse(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaterialsByCourse(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSessionsByCourse(arg0: CourseId): Promise<Array<ClassSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessionsByCourse(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessionsByCourse(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSessionsByTeacher(arg0: TeacherId): Promise<Array<ClassSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessionsByTeacher(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessionsByTeacher(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return result;
        }
    }
    async listTeachers(): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers();
            return result;
        }
    }
    async recordAttendance(arg0: CreateAttendanceArgs): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(to_candid_CreateAttendanceArgs_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AttendanceRecord_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(to_candid_CreateAttendanceArgs_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AttendanceRecord_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordMark(arg0: CreateMarkArgs): Promise<Mark> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMark(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async unenrollStudentFromCourse(arg0: StudentId, arg1: CourseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unenrollStudentFromCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unenrollStudentFromCourse(arg0, arg1);
            return result;
        }
    }
    async updateCourse(arg0: CourseId, arg1: UpdateCourseArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1);
            return result;
        }
    }
    async updateFee(arg0: FeeId, arg1: UpdateFeeArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFee(arg0, to_candid_UpdateFeeArgs_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFee(arg0, to_candid_UpdateFeeArgs_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSession(arg0: ScheduleId, arg1: UpdateSessionArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSession(arg0, to_candid_UpdateSessionArgs_n55(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSession(arg0, to_candid_UpdateSessionArgs_n55(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudent(arg0: StudentId, arg1: UpdateStudentArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return result;
        }
    }
    async updateTeacher(arg0: TeacherId, arg1: UpdateTeacherArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, arg1);
            return result;
        }
    }
    async uploadMaterial(arg0: CreateMaterialArgs): Promise<StudyMaterial> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMaterial(await to_candid_CreateMaterialArgs_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StudyMaterial_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMaterial(await to_candid_CreateMaterialArgs_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StudyMaterial_n31(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AttendanceRecord_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ClassSession_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassSession): ClassSession {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ClassStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassStatus): ClassStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeeStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStatus): FeeStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FeeTransaction_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeTransaction): FeeTransaction {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FeeType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeType): FeeType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialType): MaterialType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_StudyMaterial_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMaterial): Promise<StudyMaterial> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Batch]): Batch | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeTransaction]): FeeTransaction | null {
    return value.length === 0 ? null : from_candid_FeeTransaction_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyMaterial]): Promise<StudyMaterial | null> {
    return value.length === 0 ? null : await from_candid_StudyMaterial_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeacherProfile]): TeacherProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClassSession]): ClassSession | null {
    return value.length === 0 ? null : from_candid_ClassSession_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeeId;
    status: _FeeStatus;
    studentId: _StudentId;
    createdAt: _Timestamp;
    feeType: _FeeType;
    dueDate: _Timestamp;
    paidDate: [] | [_Timestamp];
    notes: string;
    amount: bigint;
}): {
    id: FeeId;
    status: FeeStatus;
    studentId: StudentId;
    createdAt: Timestamp;
    feeType: FeeType;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_FeeStatus_n16(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        createdAt: value.createdAt,
        feeType: from_candid_FeeType_n18(_uploadFile, _downloadFile, value.feeType),
        dueDate: value.dueDate,
        paidDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.paidDate)),
        notes: value.notes,
        amount: value.amount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScheduleId;
    status: _ClassStatus;
    topic: string;
    duration: bigint;
    date: _Timestamp;
    createdAt: _Timestamp;
    time: string;
    teacherId: _TeacherId;
    courseId: _CourseId;
}): {
    id: ScheduleId;
    status: ClassStatus;
    topic: string;
    duration: bigint;
    date: Timestamp;
    createdAt: Timestamp;
    time: string;
    teacherId: TeacherId;
    courseId: CourseId;
} {
    return {
        id: value.id,
        status: from_candid_ClassStatus_n23(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        duration: value.duration,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        teacherId: value.teacherId,
        courseId: value.courseId
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MaterialId;
    title: string;
    fileBlob: _ExternalBlob;
    description: string;
    fileName: string;
    courseId: _CourseId;
    uploadDate: _Timestamp;
    materialType: _MaterialType;
    uploadedBy: _TeacherId;
}): Promise<{
    id: MaterialId;
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    courseId: CourseId;
    uploadDate: Timestamp;
    materialType: MaterialType;
    uploadedBy: TeacherId;
}> {
    return {
        id: value.id,
        title: value.title,
        fileBlob: await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        fileName: value.fileName,
        courseId: value.courseId,
        uploadDate: value.uploadDate,
        materialType: from_candid_MaterialType_n34(_uploadFile, _downloadFile, value.materialType),
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: _Timestamp;
    markedBy: _TeacherId;
    notes: string;
    courseId: _CourseId;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    markedBy: TeacherId;
    notes: string;
    courseId: CourseId;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n42(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        markedBy: value.markedBy,
        notes: value.notes,
        courseId: value.courseId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
}): FeeStatus {
    return "paid" in value ? FeeStatus.paid : "unpaid" in value ? FeeStatus.unpaid : "partial" in value ? FeeStatus.partial : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    quarterly: null;
} | {
    monthly: null;
}): FeeType {
    return "annual" in value ? FeeType.annual : "quarterly" in value ? FeeType.quarterly : "monthly" in value ? FeeType.monthly : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): ClassStatus {
    return "upcoming" in value ? ClassStatus.upcoming : "cancelled" in value ? ClassStatus.cancelled : "completed" in value ? ClassStatus.completed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resource: null;
} | {
    assignment: null;
} | {
    notes: null;
}): MaterialType {
    return "resource" in value ? MaterialType.resource : "assignment" in value ? MaterialType.assignment : "notes" in value ? MaterialType.notes : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    late: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeTransaction>): Array<FeeTransaction> {
    return value.map((x)=>from_candid_FeeTransaction_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyMaterial>): Promise<Array<StudyMaterial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StudyMaterial_n31(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassSession>): Array<ClassSession> {
    return value.map((x)=>from_candid_ClassSession_n21(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_ClassStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassStatus): _ClassStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_CreateAttendanceArgs_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAttendanceArgs): _CreateAttendanceArgs {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_CreateFeeArgs_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFeeArgs): _CreateFeeArgs {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateMaterialArgs_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMaterialArgs): Promise<_CreateMaterialArgs> {
    return await to_candid_record_n60(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FeeStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeStatus): _FeeStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_FeeType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeType): _FeeType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MaterialType_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialType): _MaterialType {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFeeArgs_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFeeArgs): _UpdateFeeArgs {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSessionArgs_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSessionArgs): _UpdateSessionArgs {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: StudentId;
    feeType: FeeType;
    dueDate: Timestamp;
    notes: string;
    amount: bigint;
}): {
    studentId: _StudentId;
    feeType: _FeeType;
    dueDate: _Timestamp;
    notes: string;
    amount: bigint;
} {
    return {
        studentId: value.studentId,
        feeType: to_candid_FeeType_n12(_uploadFile, _downloadFile, value.feeType),
        dueDate: value.dueDate,
        notes: value.notes,
        amount: value.amount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    notes: string;
    courseId: CourseId;
}): {
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: _Timestamp;
    notes: string;
    courseId: _CourseId;
} {
    return {
        status: to_candid_AttendanceStatus_n49(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        notes: value.notes,
        courseId: value.courseId
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: FeeStatus;
    feeType: FeeType;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    notes: string;
    amount: bigint;
}): {
    status: _FeeStatus;
    feeType: _FeeType;
    dueDate: _Timestamp;
    paidDate: [] | [_Timestamp];
    notes: string;
    amount: bigint;
} {
    return {
        status: to_candid_FeeStatus_n53(_uploadFile, _downloadFile, value.status),
        feeType: to_candid_FeeType_n12(_uploadFile, _downloadFile, value.feeType),
        dueDate: value.dueDate,
        paidDate: value.paidDate ? candid_some(value.paidDate) : candid_none(),
        notes: value.notes,
        amount: value.amount
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ClassStatus;
    topic: string;
    duration: bigint;
    date: Timestamp;
    time: string;
}): {
    status: _ClassStatus;
    topic: string;
    duration: bigint;
    date: _Timestamp;
    time: string;
} {
    return {
        status: to_candid_ClassStatus_n57(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        duration: value.duration,
        date: value.date,
        time: value.time
    };
}
async function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    fileBlob: ExternalBlob;
    description: string;
    fileName: string;
    courseId: CourseId;
    materialType: MaterialType;
}): Promise<{
    title: string;
    fileBlob: _ExternalBlob;
    description: string;
    fileName: string;
    courseId: _CourseId;
    materialType: _MaterialType;
}> {
    return {
        title: value.title,
        fileBlob: await to_candid_ExternalBlob_n61(_uploadFile, _downloadFile, value.fileBlob),
        description: value.description,
        fileName: value.fileName,
        courseId: value.courseId,
        materialType: to_candid_MaterialType_n62(_uploadFile, _downloadFile, value.materialType)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeType): {
    annual: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} {
    return value == FeeType.annual ? {
        annual: null
    } : value == FeeType.quarterly ? {
        quarterly: null
    } : value == FeeType.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.late ? {
        late: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeStatus): {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
} {
    return value == FeeStatus.paid ? {
        paid: null
    } : value == FeeStatus.unpaid ? {
        unpaid: null
    } : value == FeeStatus.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassStatus): {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == ClassStatus.upcoming ? {
        upcoming: null
    } : value == ClassStatus.cancelled ? {
        cancelled: null
    } : value == ClassStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialType): {
    resource: null;
} | {
    assignment: null;
} | {
    notes: null;
} {
    return value == MaterialType.resource ? {
        resource: null
    } : value == MaterialType.assignment ? {
        assignment: null
    } : value == MaterialType.notes ? {
        notes: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
